<?php /** @var $block \DIW\ReferralCandy\Block\OrderConfirmation */ ?>
<?php if ($block->getReferralCandyEnabled() && $block->getOrderId()) : ?>
<div
  id="refcandy-mint"
  data-app-id="<?= $block->escapeHtmlAttr($block->getReferralCandyAppId()); ?>"
  data-fname="<?= $block->escapeHtmlAttr($block->getCustomerFirstname()); ?>"
  data-lname="<?= $block->escapeHtmlAttr($block->getCustomerLastname()); ?>"
  data-email="<?= $block->escapeHtmlAttr($block->getCustomerEmail()); ?>"
  data-amount="<?= $block->escapeHtmlAttr($block->getOrderSubtotal()); ?>"
  data-currency="<?= $block->escapeHtmlAttr($block->getOrderCurrencyCode()); ?>"
  data-timestamp="<?= $block->escapeHtmlAttr($block->getOrderTimestamp()); ?>"
  data-external-reference-id="<?= $block->escapeHtmlAttr($block->getOrderId()); ?>"
  data-signature="<?= $block->escapeHtmlAttr($block->getReferralCandySignature()); ?>"
></div>
<script>(function(e){var t,n,r,i,s,o,u,a,f,l,c,h,p,d,v;z="script";l="refcandy-purchase-js";c="refcandy-mint";p="go.referralcandy.com/purchase/";t="data-app-id";r={email:"a",fname:"b",lname:"c",amount:"d",currency:"e","accepts-marketing":"f",timestamp:"g","referral-code":"h",locale:"i","external-reference-id":"k",signature:"ab"};i=e.getElementsByTagName(z)[0];s=function(e,t){if(t){return""+e+"="+encodeURIComponent(t)}else{return""}};d=function(e){return""+p+h.getAttribute(t)+".js?aa=75&"};if(!e.getElementById(l)){h=e.getElementById(c);if(h){o=e.createElement(z);o.id=l;a=function(){var e;e=[];for(n in r){u=r[n];v=h.getAttribute("data-"+n);e.push(s(u,v))}return e}();o.src="//"+d(h.getAttribute(t))+a.join("&");return i.parentNode.insertBefore(o,i)}}})(document);</script>
<?php endif; ?>
